# site settings
title: Amethix Technologies
logo: assets/images/amethix-logo-white.png
subtitle:
email: hello@amethix.com
description: High quality data and technology empower people and organizations to ask and answer complex questions. We create products that transform the way institutions use their data and solve hard problems.
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://amethix.com # the base hostname & protocol for your site
author: Amethix Technologies
street_address: 1 Stadsvest
city: Leuven
state: Belgium
zip_code: 3012
country: Belgium
phone: (+32) 478998936

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/amethix
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/fragadaleta
pinterest_url:
slack_url:
twitter_url: https://twitter.com/thisisfrag

# build settings
markdown: kramdown

sass:
  style: compressed
